# Generated by Django 4.2 on 2023-05-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_gallary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallary',
            new_name='Gallery',
        ),
    ]
