# Generated by Django 4.2 on 2023-04-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
